-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Mar 26, 2022 at 03:37 PM
-- Server version: 10.1.37-MariaDB
-- PHP Version: 7.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `locations`
--

-- --------------------------------------------------------

--
-- Table structure for table `places`
--

DROP TABLE IF EXISTS `places`;
CREATE TABLE `places` (
  `continent` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL,
  `country` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL,
  `name` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL,
  `description` mediumtext COLLATE utf8_unicode_ci,
  `landscapes` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL,
  `images` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `places`
--

INSERT INTO `places` (`continent`, `country`, `name`, `description`, `landscapes`, `images`) VALUES
('Asia', 'Uzbekistan', 'Samarkand+Samarkand+Samarcande+Samarqand', 'Samarkand is a city in Uzbekistan known for its mosques and mausoleums. It\'s on the Silk Road, the ancient trade route linking China to the Mediterranean. Prominent landmarks include the Registan, a plaza bordered by 3 ornate, majolica-covered madrassas dating to the 15th and 17th centuries, and Gur-e-Amir, the towering tomb of Timur (Tamerlane), founder of the Timurid Empire.+Samarkand ist eine Stadt in Usbekistan, die für ihre Moscheen und Mausoleen bekannt ist. Es liegt an der Seidenstraße, der alten Handelsroute, die China mit dem Mittelmeer verband. Zu den markanten Sehenswürdigkeiten gehören der Registan, ein Platz, der von 3 kunstvollen, mit Majolika bedeckten Medresen aus dem 15. und 17. Jahrhundert begrenzt wird, und Gur-e-Amir, das hoch aufragende Grab von Timur (Tamerlane), dem Gründer des Timuridenreiches.+Samarcande est une ville d\'Ouzbékistan connue pour ses mosquées et ses mausolées. C\'est sur la route de la soie, l\'ancienne route commerciale reliant la Chine à la Méditerranée. Les monuments les plus importants incluent le Registan, une place bordée de 3 madrassas ornées et couvertes de majolique datant des XVe et XVIIe siècles, et Gur-e-Amir, l\'imposant tombeau de Timur (Tamerlan), fondateur de l\'empire timuride.+Samarqand O\'zbekistondagi masjid va maqbaralari bilan mashhur shahar. Bu Xitoyni O\'rta er dengizi bilan bog\'laydigan qadimgi savdo yo\'li bo\'lgan Ipak yo\'lida. Ko\'zga ko\'ringan diqqatga sazovor joylarga Registon, 15-17-asrlarga oid 3 ta bezakli, mayolika bilan qoplangan madrasalar bilan chegaradosh maydon va Temuriylar imperiyasining asoschisi Temur (Temurlan)ning baland ko\'tarilgan maqbarasi Gur-e-Amir kiradi.', 'history, mountains, medieval, ancient', './img/samarkand.jpg, ./img/samarkand2.jpg, ./img/samarkand3.jpg'),
('Asia', 'United Arab Emirates+Vereinigte Arabische Emirate+Emirats Arabes Unis+Birlashgan Arab Amirliklari', 'Dubai', 'Dubai is a city and emirate in the United Arab Emirates known for luxury shopping, ultramodern architecture and a lively nightlife scene. Burj Khalifa, an 830m-tall tower, dominates the skyscraper-filled skyline.+Dubai ist eine Stadt und ein Emirat in den Vereinigten Arabischen Emiraten, die für luxuriöse Einkaufsmöglichkeiten, ultramoderne Architektur und ein lebhaftes Nachtleben bekannt sind. Burj Khalifa, ein 830 m hoher Turm, dominiert die mit Wolkenkratzern gefüllte Skyline.+Dubaï est une ville et un émirat des Émirats arabes unis connus pour leurs boutiques de luxe, leur architecture ultramoderne et leur vie nocturne animée. Burj Khalifa, une tour de 830 m de haut, domine l\'horizon rempli de gratte-ciel.+Dubay - Birlashgan Arab Amirliklaridagi shahar va amirlik, hashamatli xaridlar, ultramodern arxitektura va jonli tungi hayot sahnasi bilan mashhur. Balandligi 830 m bo\'lgan Burj Xalifa minorasi osmono\'par binolar bilan to\'ldirilgan osmon chizig\'ida hukmronlik qiladi.', 'sea, beach, skyscrapers, desert, ice-city', './img/dubai.jpg, ./img/dubai2.jpg, ./img/dubai3.jpg'),
('Africa', 'Egypt', 'Giza+Gizeh+Gizeh+Giza', 'Giza is an Egyptian city on the west bank of the Nile, near Cairo. The Giza Plateau is home to iconic Egyptian monuments, including 3 tall pyramids built as royal mausoleums around the 26th century B.C. The largest, the Great Pyramid, is King Khufu\'s tomb.+Gizeh ist eine ägyptische Stadt am Westufer des Nils in der Nähe von Kairo. Das Gizeh-Plateau beherbergt ikonische ägyptische Denkmäler, darunter 3 hohe Pyramiden, die um das 26. Jahrhundert v. Chr. als königliche Mausoleen erbaut wurden. Die größte, die Große Pyramide, ist das Grab von König Cheops.+Gizeh est une ville égyptienne située sur la rive ouest du Nil, près du Caire. Le plateau de Gizeh abrite des monuments égyptiens emblématiques, dont 3 grandes pyramides construites comme mausolées royaux vers le 26e siècle av. J.-C. La plus grande, la Grande Pyramide, est la tombe du roi Khufu.+Giza - Misrning Nil daryosining g\'arbiy sohilida, Qohira yaqinida joylashgan shahri. Giza platosida Misrning mashhur yodgorliklari, jumladan, miloddan avvalgi 26-asrda qirol maqbarasi sifatida qurilgan 3 ta baland piramidalar joylashgan. Eng kattasi Buyuk Piramida qirol Xufu qabridir.', 'history, desert, ancient', './img/giza.jpg, ./img/giza2.jpg, ./img/giza3.jpg'),
('South_America', 'Chile+Chile+Chili+Chili', 'Santiago', 'Santiago, Chile\'s capital and largest city, sits in a valley surrounded by the snow-capped Andes and the Chilean Coast Range. Plaza de Armas, the grand heart of the city\'s old colonial core, is home to 2 neoclassical landmarks: the 1808 Palacio de la Real Audiencia and the 18th-century Metropolitan Cathedral+Santiago, die Hauptstadt und größte Stadt Chiles, liegt in einem Tal, das von den schneebedeckten Anden und der chilenischen Küstenkette umgeben ist. Die Plaza de Armas, das große Herz des alten Kolonialkerns der Stadt, beherbergt 2 neoklassizistische Wahrzeichen: den Palacio de la Real Audiencia aus dem Jahr 1808 und die Metropolitan Cathedral aus dem 18. Jahrhundert+Santiago, la capitale et la plus grande ville du Chili, est située dans une vallée entourée par les Andes enneigées et la chaîne côtière chilienne. La Plaza de Armas, le grand cour de l\'ancien noyau colonial de la ville, abrite 2 monuments néoclassiques : le Palacio de la Real Audiencia de 1808 et la cathédrale métropolitaine du XVIIIe siècle.+Chili poytaxti va eng yirik shahri Santyago qorli And tog\'lari va Chili qirg\'oq tizmasi bilan o\'ralgan vodiyda joylashgan. Shaharning eski mustamlaka yadrosining buyuk yuragi Plaza de Armasda ikkita neoklassik diqqatga sazovor joylar joylashgan: 1808 yilgi Palacio de la Real Audiencia va 18-asrdagi Metropolitan sobori.', 'history, mountains, skyscrapers', './img/santiago.jpg, ./img/santiago2.jpg, ./img/santiago3.jpg'),
('North_America', 'US', 'Boston', 'Boston is best known for its famous baked beans, Fenway Park, The Boston Marathon, and of course for the bar from Cheers, but dig a little deeper below the surface and you\'ll find a surprising wealth of things that make Boston one of the best cities in America-and the world+Boston ist am besten bekannt für seine berühmten Baked Beans, Fenway Park, The Boston Marathon und natürlich für die Bar von Cheers, aber graben Sie etwas tiefer unter der Oberfläche und Sie werden eine überraschende Fülle von Dingen finden, die Boston zu einem der besten machen besten Städte in Amerika - und der Welt+Boston est surtout connue pour ses célèbres haricots cuits au four, Fenway Park, le marathon de Boston et bien sûr pour le bar de Cheers, mais creusez un peu plus profondément sous la surface et vous trouverez une richesse surprenante de choses qui font de Boston l\'un des meilleures villes d\'Amérique et du monde+Boston o\'zining mashhur pishirilgan fasollari, Fenway Park, Boston Marafoni va, albatta, Cheers\'dagi bari bilan mashhur, ammo yerdan biroz chuqurroq qazib oling va siz hayratlanarli boyliklarni topasiz. Bu Bostonni Amerika va dunyodagi eng yaxshi shaharlardan biriga aylantiradi', 'skyscrapers, river, sea, history', './img/boston.jpg, ./img/boston2.jpg, ./img/boston3.jpg'),
('North_America', 'US', 'Denver', 'Denver, the capital of Colorado, is an American metropolis dating to the Old West era. Larimer Square, the city\'s oldest block, features landmark 19th-century buildings. Museums include the Denver Art Museum, an ultramodern complex known for its collection of indigenous works, and the mansion of famed Titanic survivor Molly Brown+Denver, die Hauptstadt von Colorado, ist eine amerikanische Metropole aus der Ära des Alten Westens. Der Larimer Square, der älteste Block der Stadt, verfügt über markante Gebäude aus dem 19. Jahrhundert. Zu den Museen gehören das Denver Art Museum, ein hochmoderner Komplex, der für seine Sammlung einheimischer Werke bekannt ist, und das Herrenhaus der berühmten Titanic-Überlebenden Molly Brown+Denver, la capitale du Colorado, est une métropole américaine datant de l\'époque du Far West. Larimer Square, le plus ancien pâté de maisons de la ville, abrite des bâtiments emblématiques du XIXe siècle. Les musées comprennent le Denver Art Museum, un complexe ultramoderne connu pour sa collection d\'ouvres indigènes, et le manoir de la célèbre survivante du Titanic Molly Brown+Koloradoning poytaxti Denver - Qadimgi G\'arb davriga oid Amerika metropolisidir. Larimer maydoni, shaharning eng qadimgi bloki, 19-asrning diqqatga sazovor binolariga ega. Muzeylar orasida Denver san\'at muzeyi, mahalliy asarlar to\'plami bilan mashhur bo\'lgan ultramodern majmua va mashhur Titanikdan omon qolgan Molli Braunning saroyi kiradi.', 'skyscrapers, mountains, forest', './img/denver.jpg, ./img/denver2.jpg, ./img/denver3.jpg'),
('Europe', 'Poland+Polen+Pologne+Polsha', 'Gdansk+Danzig+Gdansk+Gdansk', 'Gdansk (Danzig in German) is a port city on the Baltic coast of Poland. At the center of its Main Town, reconstructed after WWII, are the colorful facades of Long Market, now home to shops and restaurants.+Gdansk (Danzig auf Deutsch) ist eine Hafenstadt an der polnischen Ostseeküste. Im Zentrum der nach dem Zweiten Weltkrieg wieder aufgebauten Hauptstadt befinden sich die farbenfrohen Fassaden des Langen Marktes, auf dem sich heute Geschäfte und Restaurants befinden.+Gdansk (Dantzig en allemand) est une ville portuaire sur la côte baltique de la Pologne. Au centre de sa ville principale, reconstruite après la Seconde Guerre mondiale, se trouvent les façades colorées du Long Market, qui abrite aujourd\'hui des boutiques et des restaurants.+Gdansk (nemischa Danzig) - Polshaning Boltiqbo?yi sohilidagi port shahri. Ikkinchi Jahon Urushidan keyin qayta qurilgan asosiy shahar markazida hozirda do\'konlar va restoranlar joylashgan Long Marketning rang-barang jabhalari joylashgan.', 'history, river, sea, medieval', './img/gdansk.jpg, ./img/gdansk2.jpg, ./img/gdansk3.jpg'),
('Asia', 'Indonesia', 'Bali', 'Bali is a province of Indonesia and the westernmost of the Lesser Sunda Islands. East of Java and west of Lombok, the province includes the island of Bali and a few smaller neighbouring islands, notably Nusa Penida, Nusa Lembongan, and Nusa Ceningan+Bali ist eine Provinz Indonesiens und die westlichste der Kleinen Sundainseln. Östlich von Java und westlich von Lombok umfasst die Provinz die Insel Bali und einige kleinere Nachbarinseln, insbesondere Nusa Penida, Nusa Lembongan und Nusa Ceningan+Bali est une province d\'Indonésie et la plus occidentale des petites îles de la Sonde. A l\'est de Java et à l\'ouest de Lombok, la province comprend l\'île de Bali et quelques petites îles voisines, notamment Nusa Penida, Nusa Lembongan et Nusa Ceningan.+Bali Indoneziyaning provinsiyasi va Kichik Sunda orollarining eng g\'arbiy qismidir. Java sharqida va Lombokdan g\'arbda joylashgan provinsiyaga Bali oroli va bir necha kichikroq qo\'shni orollar, xususan Nusa Penida, Nusa Lembongan va Nusa Ceningan kiradi.', 'beach, sea, history, mountains', './img/bali.jpg, ./img/bali2.jpg, ./img/bali3.jpg'),
('North_America', 'US', 'Los Angeles', 'Los Angeles is a sprawling Southern California city and the center of the nation\'s film and television industry. Near its iconic Hollywood sign, studios such as Paramount Pictures, Universal and Warner Brothers offer behind-the-scenes tours+Los Angeles ist eine weitläufige Stadt in Südkalifornien und das Zentrum der Film- und Fernsehindustrie des Landes. In der Nähe des berühmten Hollywood-Schriftzugs bieten Studios wie Paramount Pictures, Universal und Warner Brothers Führungen hinter die Kulissen an+Los Angeles est une ville tentaculaire du sud de la Californie et le centre de l\'industrie cinématographique et télévisuelle du pays. Près de son enseigne emblématique d\'Hollywood, des studios tels que Paramount Pictures, Universal et Warner Brothers proposent des visites des coulisses+Los-Anjeles - keng tarqalgan Janubiy Kaliforniya shahri va mamlakat kino va televidenie sanoatining markazi. Gollivudning ramziy belgisi yonida Paramount Pictures, Universal va Warner Brothers kabi studiyalar sahna ortidagi sayohatlarni taklif qilishadi.', 'skyscrapers, beach, mountains', './img/LA.jpg, ./img/LA2.jpg, ./img/LA3.jpg'),
('Australia_Oceania', 'Australia+Australien+Australie+Avstraliya', 'Melbourne', 'Melbourne is the coastal capital of the southeastern Australian state of Victoria. At the city\'s centre is the modern Federation Square development, with plazas, bars, and restaurants by the Yarra River.+Melbourne ist die Küstenhauptstadt des südostaustralischen Bundesstaates Victoria. Im Zentrum der Stadt befindet sich die moderne Entwicklung des Federation Square mit Plätzen, Bars und Restaurants am Yarra River.+Melbourne est la capitale côtière de l\'État de Victoria, dans le sud-est de l\'Australie. Au centre de la ville se trouve le développement moderne de Federation Square, avec des places, des bars et des restaurants au bord de la rivière Yarra.+Melburn - Avstraliyaning janubi-sharqidagi Viktoriya shtatining qirg\'oq bo\'yi poytaxti. Shahar markazida Yarra daryosi bo\'yida plazalar, barlar va restoranlar joylashgan zamonaviy Federatsiya maydoni joylashgan.', 'skyscrapers, beach, river, sea', './img/melbourne.jpg, ./img/melbourne2.jpg, ./img/melbourne3.jpeg'),
('North_America', 'US', 'Miami+Miami+Miami+Mayami', 'Miami, officially the City of Miami, is a coastal metropolis located in Miami-Dade County in southeastern Florida. With a population of 467,968 as of the 2020 census, it is the second-most populous city in Florida, eleventh-most populous city in the Southeast+Miami, offiziell die Stadt Miami, ist eine Küstenmetropole im Miami-Dade County im Südosten Floridas. Mit einer Bevölkerung von 467.968 bei der Volkszählung 2020 ist es die zweitbevölkerungsreichste Stadt in Florida und die elftgrößte Stadt im Südosten+Miami, officiellement la ville de Miami, est une métropole côtière située dans le comté de Miami-Dade, dans le sud-est de la Floride. Avec une population de 467 968 habitants au recensement de 2020, c\'est la deuxième ville la plus peuplée de Floride, la onzième ville la plus peuplée du sud-est.+Mayami, rasman Mayami shahri, Florida janubi-sharqidagi Mayami-Deyd okrugida joylashgan qirg\'oq bo\'yidagi metropoldir. 2020 yilgi aholini ro\'yxatga olish ma\'lumotlariga ko\'ra 467,968 aholiga ega bo\'lib, u Floridadagi ikkinchi eng zich shahar, janubi-sharqdagi aholi soni bo\'yicha o\'n birinchi shahar.', 'skyscrapers, beach, river, sea', './img/miami.jpeg, ./img/miami2.jpg, ./img/miami4.jpg'),
('South_America', 'Uruguay+Uruguay+Uruguay+Urugvay', 'Montevidéo', 'Montevideo, Uruguay\'s capital, is a major city along Montevideo Bay. It revolves around the Plaza de la Independencia, once home to a Spanish citadel. This plaza leads to Ciudad Vieja (the old town), with art deco buildings, colonial homes and landmarks including the towering Palacio Salvo and neoclassical performance hall Solís Theatre+Montevideo, die Hauptstadt von Uruguay, ist eine Großstadt an der Bucht von Montevideo. Es dreht sich um die Plaza de la Independencia, die einst eine spanische Zitadelle beherbergte. Dieser Platz führt zu Ciudad Vieja (der Altstadt) mit Art-Deco-Gebäuden, Kolonialhäusern und Sehenswürdigkeiten wie dem hoch aufragenden Palacio Salvo und dem neoklassizistischen Theater Solís.+Montevideo, la capitale de l\'Uruguay, est une grande ville le long de la baie de Montevideo. Il s\'articule autour de la Plaza de la Independencia, qui abritait autrefois une citadelle espagnole. Cette place mène à Ciudad Vieja (la vieille ville), avec des bâtiments Art déco, des maisons coloniales et des monuments tels que l\'imposant Palacio Salvo et la salle de spectacle néoclassique Solís Theatre.+Urugvay poytaxti Montevideo, Montevideo ko\'rfazi bo\'ylab joylashgan yirik shahar. U bir vaqtlar ispan qal\'asi joylashgan Plaza de la Independencia atrofida aylanadi. Bu maydon Syudad Viejaga (eski shahar) olib boradi, unda art deko binolari, mustamlakachilik uylari va diqqatga sazovor joylari, jumladan, baland Palacio Salvo va neoklassik zal Solis teatri mavjud.', 'beach, sea, history', './img/montevideo.jpg, ./img/montevideo2.jpg, ./img/montevideo3.jpg'),
('Africa', 'Kenya+Kenia+Kenya+Keniya', 'Nairobi+Nairobi+Nairobi+Nayrobi', 'Nairobi is Kenya\'s capital city. In addition to its urban core, the city has Nairobi National Park, a large game reserve known for breeding endangered black rhinos and home to giraffes, zebras and lions. Next to it is a well-regarded elephant orphanage. Nairobi is also often used as a jumping-off point for safari trips elsewhere in Kenya+Nairobi ist Kenias Hauptstadt. Neben dem Stadtkern verfügt die Stadt über den Nairobi-Nationalpark, ein großes Wildreservat, das für die Aufzucht gefährdeter Spitzmaulnashörner und die Heimat von Giraffen, Zebras und Löwen bekannt ist. Daneben befindet sich ein angesehenes Elefantenwaisenhaus. Nairobi wird auch oft als Ausgangspunkt für Safarireisen in andere Teile Kenias genutzt+Nairobi est la capitale du Kenya. En plus de son noyau urbain, la ville possède le parc national de Nairobi, une grande réserve de gibier connue pour l\'élevage de rhinocéros noirs en voie de disparition et abritant des girafes, des zèbres et des lions. A côté se trouve un orphelinat d\'éléphants réputé. Nairobi est également souvent utilisée comme point de départ pour des safaris ailleurs au Kenya.+Nayrobi - Keniyaning poytaxti. Shahar markazidan tashqari, shaharda Nayrobi milliy bog\'i, yo\'qolib ketish xavfi ostida turgan qora karkidonlarni ko\'paytirish bilan mashhur va jirafalar, zebralar va sherlar yashaydigan yirik qo\'riqxona mavjud. Uning yonida yaxshi hurmatga sazovor bo\'lgan fillar uyi joylashgan. Nayrobi, shuningdek, Keniyaning boshqa joylariga safari sayohatlari uchun sakrash nuqtasi sifatida ham ishlatiladi', 'skyscrapers, history, wildlife', './img/nairobi.jpg, ./img/nairobi2.jpg, ./img/nairobi3.jpg'),
('Asia', 'China+China+Chine+Xitoy', 'Hong Kong', 'The tourism industry has been an important part of the economy of Hong Kong since it shifted to a service sector model in the late 1980s and early 90s. There has been a sharp increase of domestic tourists from Mainland China+Die Tourismusbranche ist ein wichtiger Teil der Wirtschaft Hongkongs, seit sie Ende der 1980er und Anfang der 90er Jahre zu einem Dienstleistungssektormodell übergegangen ist. Es gab einen starken Anstieg von Inlandstouristen aus Festlandchina.+L\'industrie du tourisme a été une partie importante de l\'économie de Hong Kong depuis qu\'elle est passée à un modèle de secteur des services à la fin des années 80 et au début des années 90. Il y a eu une forte augmentation des touristes nationaux en provenance de Chine continentale.+Turizm sanoati 1980-yillarning oxiri va 90-yillarning boshlarida xizmat ko\'rsatish sohasi modeliga o\'tgandan beri Gonkong iqtisodiyotining muhim qismi bo\'ldi. Materik Xitoydan mahalliy sayyohlar soni keskin oshgan.', 'history, sea, skyscrapers, mountains', './img/hongkong.jpg, ./img/hongkong2.jpg, ./img/hongkong3.jpeg'),
('Europe', 'Spain+Spanien+Espagne+Ispaniya', 'Barcelona+Barcelona+Barcelone+Barselona', 'Barcelona, the cosmopolitan capital of Spain\'s Catalonia region, is known for its art and architecture. The fantastical Sagrada Família church and other modernist landmarks designed by Antoni Gaudí dot the city. Museu Picasso and Fundació Joan Miró feature modern art by their namesakes.+Barcelona, die kosmopolitische Hauptstadt der spanischen Region Katalonien, ist bekannt für ihre Kunst und Architektur. Die fantastische Kirche Sagrada Família und andere modernistische Wahrzeichen, die von Antoni Gaudí entworfen wurden, prägen die Stadt. Das Museu Picasso und die Fundació Joan Miró zeigen moderne Kunst ihrer Namensgeber.+Barcelone, la capitale cosmopolite de la région espagnole de Catalogne, est connue pour son art et son architecture. La fantastique église Sagrada Família et d\'autres monuments modernistes conçus par Antoni Gaudí parsèment la ville. Le Museu Picasso et la Fundació Joan Miró présentent l\'art moderne par leurs homonymes.+Barselona, Ispaniyaning Kataloniya mintaqasining kosmopolit poytaxti, o\'zining san\'ati va me\'morchiligi bilan mashhur. Antoni Gaudi tomonidan ishlab chiqilgan hayoliy Sagrada Familia cherkovi va boshqa modernistik diqqatga sazovor joylar shaharga nuqta qo\'ygan. Museu Picasso va Fundació Joan Miro zamonaviy san\'atni o\'z nomlari bilan namoyish etadi.', 'history, sea, beach, skyscrapers', './img/barca.jpg, ./img/barca2.jpg, ./img/barca3.jpg'),
('Australia_Oceania', 'Australia+Australien+Australie+Avstraliya', 'Sydney', 'Sydney, capital of New South Wales and one of Australia\'s largest cities, is best known for its harbourfront Sydney Opera House, with a distinctive sail-like design. Massive Darling Harbour and the smaller Circular Quay port are hubs of waterside life, with the arched Harbour Bridge and esteemed Royal Botanic Garden nearby.+Sydney, die Hauptstadt von New South Wales und eine der größten Städte Australiens, ist vor allem für das am Hafen gelegene Sydney Opera House mit seinem markanten segelartigen Design bekannt. Der gewaltige Darling Harbour und der kleinere Hafen Circular Quay sind Zentren des Lebens am Wasser, mit der gewölbten Harbour Bridge und dem angesehenen Royal Botanic Garden in der Nähe.+Sydney, capitale de la Nouvelle-Galles du Sud et l\'une des plus grandes villes d\'Australie, est surtout connue pour son opéra de Sydney en front de mer, avec un design distinctif en forme de voile. L\'immense port de Darling Harbour et le plus petit port de Circular Quay sont des centres de vie au bord de l\'eau, avec le pont en arc du port et le célèbre jardin botanique royal à proximité.+Yangi Janubiy Uelsning poytaxti va Avstraliyaning eng yirik shaharlaridan biri bo\'lgan Sidney o\'zining port bo\'yidagi Sidney opera teatri bilan mashhur bo\'lib, o\'ziga xos yelkanli dizayni bilan ajralib turadi. Massive Darling Harbor va kichikroq Circular Quay porti qirg\'oq bo\'yidagi hayot markazlari bo\'lib, uning yonida kemerli Harbor ko\'prigi va hurmatli Qirollik botanika bog\'i joylashgan.', 'history, sea, river, skyscrapers', './img/sydney.jpg, ./img/sydney2.jpg, ./img/sydney3.jpg'),
('Australia_Oceania', 'NZ', 'Auckland+Auckland+Auckland+Oklend', 'Auckland, based around 2 large harbours, is a major city in the north of New Zealand\'s North Island. In the centre, the iconic Sky Tower has views of Viaduct Harbour, which is full of superyachts and lined with bars and cafes.+Auckland, mit zwei großen Häfen, ist eine Großstadt im Norden der neuseeländischen Nordinsel. In der Mitte bietet der ikonische Sky Tower einen Blick auf den Viaduct Harbour, der voller Superyachten ist und von Bars und Cafés gesäumt wird.+Auckland, basée autour de 2 grands ports, est une grande ville du nord de l\'île du Nord de la Nouvelle-Zélande. Au centre, l\'emblématique Sky Tower offre une vue sur Viaduct Harbour, qui regorge de superyachts et bordée de bars et de cafés.+Ikkita yirik portga asoslangan Oklend Yangi Zelandiyaning Shimoliy orolining shimolidagi yirik shahardir. Markazdagi mashhur Sky Tower superyaxtalar bilan to\'la va barlar va kafelar bilan qoplangan Viaduct Harbour manzarasiga ega.', 'history, sea, skyscrapers', './img/auckland.jpg, ./img/auckland2.jpg, ./img/auckland3.jpg'),
('Asia', 'Thailand+Thailand+Thailande+Tailand', 'Phuket', 'Phuket, a rainforested, mountainous island in the Andaman Sea, has some of Thailand\'s most popular beaches, mainly situated along the clear waters of the western shore. The island is home to many high-end seaside resorts, spas and restaurants.+Phuket, eine bewaldete, bergige Insel in der Andamanensee, hat einige der beliebtesten Strände Thailands, die hauptsächlich entlang des klaren Wassers der Westküste liegen. Die Insel beherbergt viele hochwertige Badeorte, Spas und Restaurants.+Phuket, une île montagneuse couverte de forêts tropicales dans la mer d\'Andaman, possède certaines des plages les plus populaires de Thaïlande, principalement situées le long des eaux claires de la côte ouest. L\'île abrite de nombreuses stations balnéaires haut de gamme, des spas et des restaurants.+Andaman dengizidagi yomg\'irli o\'rmonli, tog\'li orol Pxuketda Tailandning eng mashhur plyajlari bor, ular asosan g\'arbiy qirg\'oqning toza suvlari bo\'yida joylashgan. Orolda dengiz bo\'yidagi ko\'plab yuqori darajadagi kurortlar, kurortlar va restoranlar joylashgan.', 'sea, mountains, beach', './img/phuket.jpg, ./img/phuket2.jpg, ./img/phuket4.jpg'),
('Europe', 'Germany+Deutschland+Allemagne+Germaniya', 'Hamburg+Hamburg+Hambourg+Hamburg', 'Hamburg, a major port city in northern Germany, is connected to the North Sea by the Elbe River. It\'s crossed by hundreds of canals, and also contains large areas of parkland. Near its core, Inner Alster lake is dotted with boats and surrounded by cafes+Hamburg, eine große Hafenstadt in Norddeutschland, ist durch die Elbe mit der Nordsee verbunden. Es wird von Hunderten von Kanälen durchzogen und umfasst auch große Parklandschaften. In der Nähe seines Kerns ist die Binnenalster mit Booten übersät und von Cafés umgeben+Hambourg, grande ville portuaire du nord de l\'Allemagne, est reliée à la mer du Nord par l\'Elbe. Il est traversé par des centaines de canaux et contient également de vastes espaces verts. Près de son centre, le lac Inner Alster est parsemé de bateaux et entouré de cafés+Germaniya shimolidagi yirik port shahri bo\'lgan Gamburg Shimoliy dengiz bilan Elba daryosi orqali bog\'langan. U yuzlab kanallar orqali o\'tadi, shuningdek, parklarning katta maydonlarini o\'z ichiga oladi. Ichki Alster ko\'li o\'zining yaqinida qayiqlar bilan bezatilgan va kafelar bilan o\'ralgan.', 'history, river, medieval', './img/hamburg.jpg, ./img/hamburg2.jpg, ./img/hamburg3.jpg'),
('Europe', 'CZ', 'Prague+Prag+Prague+Praga', 'Prague, capital city of the Czech Republic, is bisected by the Vltava River. Nicknamed “the City of a Hundred Spires,” it\'s known for its Old Town Square, the heart of its historic core, with colorful baroque buildings, Gothic churches and the medieval Astronomical Clock, which gives an animated hourly show.+ Prag, die Hauptstadt der Tschechischen Republik, wird von der Moldau durchschnitten. Die Stadt mit dem Spitznamen „die Stadt der hundert Türme“ ist bekannt für ihren Altstädter Ring, das Herz des historischen Kerns, mit farbenfrohen Barockgebäuden, gotischen Kirchen und der mittelalterlichen astronomischen Uhr, die stündlich eine animierte Show bietet.+Prague, capitale de la République tchèque, est traversée par la rivière Vltava. Surnommée « la ville aux cent flèches », elle est connue pour sa place de la vieille ville, le cœur de son centre historique, avec ses bâtiments baroques colorés, ses églises gothiques et l\'horloge astronomique médiévale, qui donne un spectacle animé toutes les heures.+Praga, Chexiya Respublikasining poytaxti Vltava daryosi bilan ikkiga bo\'lingan. “Yuz shpillar shahri” laqabini olgan bu shahar oʻzining tarixiy markazining yuragi boʻlgan Eski shahar maydoni, rang-barang barokko binolari, gotika cherkovlari va animatsion soatlik shoularni taqdim etuvchi oʻrta asr astronomik soati bilan mashhur.', 'history, river, hils, medieval', './img/prague.jpg, ./img/prague2.jpg, ./img/prague3.jpg'),
('Europe', 'GB', 'London+London+Londres+London', 'London, the capital of England and the United Kingdom, is a 21st-century city with history stretching back to Roman times. At its centre stand the imposing Houses of Parliament, the iconic ‘Big Ben’ clock tower and Westminster Abbey, site of British monarch coronations. Across the Thames River, the London Eye observation wheel provides panoramic views of the city+London, die Hauptstadt Englands und des Vereinigten Königreichs, ist eine Stadt des 21. Jahrhunderts, deren Geschichte bis in die Römerzeit zurückreicht. In seiner Mitte stehen die imposanten Houses of Parliament, der ikonische Glockenturm „Big Ben“ und die Westminster Abbey, Ort der Krönung britischer Monarchen. Auf der anderen Seite der Themse bietet das Aussichtsrad London Eye einen Panoramablick auf die Stadt+Londres, capitale de l\'Angleterre et du Royaume-Uni, est une ville du XXIe siècle dont l\'histoire remonte à l\'époque romaine. En son centre se dressent les imposantes chambres du Parlement, l\'emblématique tour de l\'horloge «Big Ben» et l\'abbaye de Westminster, site des couronnements des monarques britanniques. De l\'autre côté de la Tamise, la roue d\'observation du London Eye offre une vue panoramique sur la ville+Angliya va Birlashgan Qirollikning poytaxti London 21-asr tarixi Rim davriga borib taqaladigan shahardir. Uning markazida parlamentning maftunkor uylari, mashhur \"Big Ben\" soat minorasi va Britaniya monarxining toj kiyish marosimi o\'tkaziladigan Vestminster abbatligi joylashgan. Temza daryosi bo\'ylab London Eye kuzatuv g\'ildiragi shaharning panoramik ko\'rinishini taqdim etadi', 'river, history, skyscrapers, medieval', './img/london.jpg, ./img/london2.jpg, ./img/london3.jpg'),
('Europe', 'France+Frankreich+La France+Fransiya', 'Paris+Paris+Paris+Parij', 'Paris is one of the most beautiful cities in the world. It is known worldwide for the Louvre Museum, Notre-Dame cathedral, and the Eiffel tower. It has a reputation of being a romantic and cultural city. The city is also known for its high-quality gastronomy and the terraces of its cafés+Paris ist eine der schönsten Städte der Welt. Es ist weltweit bekannt für das Louvre-Museum, die Kathedrale Notre-Dame und den Eiffelturm. Es hat den Ruf, eine romantische und kulturelle Stadt zu sein. Die Stadt ist auch für ihre hochwertige Gastronomie und die Terrassen ihrer Cafés bekannt+Paris est l\'une des plus belles villes du monde. Il est connu dans le monde entier pour le musée du Louvre, la cathédrale Notre-Dame et la tour Eiffel. Elle a la réputation d\'être une ville romantique et culturelle. La ville est également connue pour sa gastronomie de qualité et les terrasses de ses cafés+Parij dunyodagi eng go\'zal shaharlardan biridir. U butun dunyoga Luvr muzeyi, Notr-Dam sobori va Eyfel minorasi bilan mashhur. U romantik va madaniy shahar sifatida obro\'ga ega. Shahar o\'zining yuqori sifatli gastronomiyasi va kafelarining teraslari bilan ham mashhur', 'history, river, skyscrapers, medieval', './img/paris.jpg, ./img/paris2.jpg, ./img/paris3.jpg'),
('South_America', 'Brazil+Brasilien+Brésil+Braziliya', 'Rio de Janeiro+Rio de Janeiro+Rio de Janeiro+Rio de Janeyro', 'Rio de Janeiro is a huge seaside city in Brazil, famed for its Copacabana and Ipanema beaches, 38m Christ the Redeemer statue atop Mount Corcovado and for Sugarloaf Mountain, a granite peak with cable cars to its summit. The city is also known for its sprawling favelas (shanty towns). Its raucous Carnaval festival, featuring parade floats, flamboyant costumes and samba dancers, is considered the world’s largest.+Rio de Janeiro ist eine riesige Küstenstadt in Brasilien, berühmt für ihre Strände Copacabana und Ipanema, die 38 m hohe Christus-Erlöser-Statue auf dem Berg Corcovado und den Zuckerhut, einen Granitgipfel mit Seilbahnen zu seinem Gipfel. Die Stadt ist auch für ihre weitläufigen Favelas (Elendsviertel) bekannt. Sein lärmendes Karnevalsfest mit Festwagen, extravaganten Kostümen und Samba-Tänzern gilt als das größte der Welt.+Rio de Janeiro est une immense ville balnéaire du Brésil, célèbre pour ses plages de Copacabana et d\'Ipanema, la statue du Christ Rédempteur de 38 m au sommet du mont Corcovado et pour le mont Sugarloaf, un pic de granit avec des téléphériques jusqu\'à son sommet. La ville est également connue pour ses favelas tentaculaires (bidonvilles). Son festival Carnaval bruyant, avec des chars de parade, des costumes flamboyants et des danseurs de samba, est considéré comme le plus grand du monde.+Rio-de-Janeyro Braziliyadagi dengiz bo\'yidagi ulkan shahar bo\'lib, o\'zining Kopakabana va Ipanema plyajlari, Korkovado tog\'idagi 38 m balandlikdagi Qutqaruvchi Masih haykali va cho\'qqisiga teleferiklar o\'rnatilgan granit cho\'qqisi Shakarloaf tog\'i bilan mashhur. Shahar o\'zining keng tarqalgan favelalari (shovqin shaharchalari) bilan ham mashhur. Uning shov-shuvli Karnaval festivali, parad suzuvchilari, ajoyib liboslari va samba raqqosalari dunyodagi eng katta hisoblanadi.', 'history, sea, skyscrapers, mountains', './img/rio.jpg, ./img/rio2.jpg, ./img/rio3.jpg'),
('South_America', 'Chile+Chile+Chili+Chili', 'San Pedro de Atacama+San Pedro de Atacama+San Pedro de Atacama+San-Pedro-de Atakama', 'San Pedro de Atacama is a town set on an arid high plateau in the Andes mountains of northeastern Chile. Its dramatic surrouding landscape incorporates desert, salt flats, volcanoes, geysers and hot springs. The Valle de la Luna in the nearby Los Flamencos National Reserve is a lunarlike depression with unusual rock formations, a huge sand dune and pink-streaked mountains+San Pedro de Atacama ist eine Stadt auf einem trockenen Hochplateau in den Anden im Nordosten Chiles. Seine dramatische Landschaft umgibt Wüste, Salinen, Vulkane, Geysire und heiße Quellen. Das Valle de la Luna im nahe gelegenen Nationalreservat Los Flamencos ist eine mondähnliche Senke mit ungewöhnlichen Felsformationen, einer riesigen Sanddüne und rosa gestreiften Bergen+San Pedro de Atacama est une ville située sur un haut plateau aride dans les Andes du nord-est du Chili. Son paysage environnant spectaculaire comprend un désert, des salines, des volcans, des geysers et des sources chaudes. La Valle de la Luna, dans la réserve nationale Los Flamencos voisine, est une dépression lunaire avec des formations rocheuses inhabituelles, une immense dune de sable et des montagnes striées de rose+San-Pedro-de-Atakama - Chili shimoli-sharqidagi And tog\'laridagi qurg\'oqchil baland platoda joylashgan shahar. Uning ajoyib manzarasi cho\'l, tuzli tekisliklar, vulqonlar, geyzerlar va issiq buloqlarni o\'z ichiga oladi. Yaqin atrofdagi Los Flamenkos milliy qo\'riqxonasidagi Valle de la Luna - bu g\'ayrioddiy qoyali shakllar, ulkan qumtepa va pushti chiziqli tog\'lardan iborat oyga o\'xshash chuqurlikdir.', 'desert, mountains', './img/sp.jpg, ./img/sp2.jpg, ./img/sp3.jpg'),
('South_America', 'Peru+Peru+Pérou+Peru', 'Cusco+Cusco+Cuzco+Kusko', 'Cusco, a city in the Peruvian Andes, was once capital of the Inca Empire, and is now known for its archaeological remains and Spanish colonial architecture. Plaza de Armas is the central square in the old city, with arcades, carved wooden balconies and Incan wall ruins.+Cusco, eine Stadt in den peruanischen Anden, war einst die Hauptstadt des Inka-Reiches und ist heute für ihre archäologischen Überreste und die spanische Kolonialarchitektur bekannt. Plaza de Armas ist der zentrale Platz in der Altstadt mit Arkaden, geschnitzten Holzbalkonen und Inka-Mauerruinen.+Cusco, une ville des Andes péruviennes, était autrefois la capitale de l\'Empire Inca et est maintenant connue pour ses vestiges archéologiques et son architecture coloniale espagnole. La Plaza de Armas est la place centrale de la vieille ville, avec des arcades, des balcons en bois sculpté et des ruines de murs incas.+Peru And tog\'laridagi Kusko shahri bir vaqtlar Inka imperiyasining poytaxti bo\'lgan va hozirda o\'zining arxeologik qoldiqlari va ispan mustamlaka me\'morchiligi bilan mashhur. Plaza de Armas - bu eski shaharning markaziy maydoni, arkadalar, o\'yilgan yog\'och balkonlar va Inka devori qoldiqlari.', 'history, mountains, medieval', './img/cusco.jpg, ./img/cusco2.jpg, ./img/cusco3.jpg'),
('Australia_Oceania', 'French Polynesia+Französisch Polynesien+Polynésie française+Fransuz Polineziyasi', 'Bora Bora+Bora Bora+Bora Bora+Bora Bora', 'Bora Bora is a small South Pacific island northwest of Tahiti in French Polynesia. Surrounded by sand-fringed motus (islets) and a turquoise lagoon protected by a coral reef, it’s known for its scuba diving. It\'s also a popular luxury resort destination where some guest bungalows are perched over the water on stilts.+Bora Bora ist eine kleine südpazifische Insel nordwestlich von Tahiti in Französisch-Polynesien. Umgeben von sandgesäumten Motus (Inseln) und einer türkisfarbenen Lagune, die von einem Korallenriff geschützt wird, ist es für sein Tauchen bekannt. Es ist auch ein beliebtes Luxusresort, wo einige Gästebungalows auf Stelzen über dem Wasser thronen.+Bora Bora est une petite île du Pacifique Sud au nord-ouest de Tahiti en Polynésie française. Entouré de motus (îlots) bordés de sable et d\'un lagon turquoise protégé par un récif corallien, il est connu pour sa plongée sous-marine. C\'est aussi une destination de villégiature de luxe populaire où certains bungalows sont perchés au-dessus de l\'eau sur des pilotis.+Bora Bora - Fransuz Polineziyasidagi Taiti shimoli-g\'arbida joylashgan Janubiy Tinch okeanidagi kichik orol. Qum qirrali motus (orolchalar) va marjon rifi bilan himoyalangan firuza lagunasi bilan o\'ralgan, u suvga sho\'ng\'in qilish bilan mashhur. Bu, shuningdek, mashhur hashamatli dam olish maskani bo\'lib, u yerda ba\'zi mehmonlar bungalovlari suv ustidagi xodalarda joylashgan.', 'mountains, sea, beach', './img/bora.jpg, ./img/bora2.jpg, ./img/bora3.jpg'),
('Asia', 'Uzbekistan+Usbekistan+Ouzbékistan+O\'zbekiston', 'Khiva+Chiwa+Khiva+Xiva', 'According to archaeological data, the city was established around 1500 years ago. Itchan Kala in Khiva was the first site in Uzbekistan to be inscribed in the World Heritage List. Khiva is split into two parts. The outer town, called Itchan Kala, was formerly protected by a wall with 11 gates. The inner town, or Itchan Kala, is encircled by brick walls, whose foundations are believed to have been laid in the 10th century.+Archäologischen Daten zufolge wurde die Stadt vor etwa 1500 Jahren gegründet. Itchan Kala in Chiwa war die erste Stätte in Usbekistan, die in die Liste des Weltkulturerbes aufgenommen wurde. Chiwa ist in zwei Teile geteilt. Die äußere Stadt, genannt Ichan Kala, wurde früher durch eine Mauer mit 11 Toren geschützt. Die Innenstadt, oder Itchan Kala, ist von Backsteinmauern umgeben, deren Fundamente vermutlich im 10. Jahrhundert gelegt wurden.+Selon les données archéologiques, la ville a été fondée il y a environ 1500 ans. Itchan Kala à Khiva a été le premier site d\'Ouzbékistan à être inscrit sur la Liste du patrimoine mondial. Khiva est divisé en deux parties. La ville extérieure, appelée Dichan Kala, était autrefois protégée par un mur avec 11 portes. Le centre-ville, ou Itchan Kala, est entouré de murs de briques, dont les fondations auraient été posées au 10ème siècle.+Arxeologik ma\'lumotlarga ko\'ra, shahar taxminan 1500 yil oldin tashkil etilgan. Xivadagi Ichan qal\'a O\'zbekistonda birinchi bo\'lib Jahon merosi ro\'yxatiga kiritilgan. Xiva ikkiga bo\'lingan. Ichan qal\'a deb nomlangan tashqi shahar ilgari 11 darvozali devor bilan himoyalangan. Ichki shahar yoki Itchan qal\'a g\'isht devorlari bilan o\'ralgan bo\'lib, uning poydevori 10-asrda qo\'yilgan deb ishoniladi.', 'history, desert, medieval, ancient', './img/xiva.jpg, ./img/xiva2.jpg, ./img/xiva3.jpg'),
('Europe', 'Belgium+Belgien+Belgique+Belgiya', 'Bruges+Brügge+Bruges+Bryugge', 'Bruges, the capital of West Flanders in northwest Belgium, is distinguished by its canals, cobbled streets and medieval buildings. Its port, Zeebrugge, is an important center for fishing and European trade. In the city center’s Burg square, the 14th-century Stadhuis (City Hall) has an ornate carved ceiling. Nearby, Markt square features a 13th-century belfry with a 47-bell carillon and 83m tower+Brügge, die Hauptstadt von Westflandern im Nordwesten Belgiens, zeichnet sich durch seine Kanäle, Kopfsteinpflasterstraßen und mittelalterlichen Gebäude aus. Sein Hafen, Zeebrugge, ist ein wichtiges Zentrum für Fischerei und europäischen Handel. Auf dem Burgplatz im Stadtzentrum hat das Stadhuis (Rathaus) aus dem 14. Jahrhundert eine kunstvoll geschnitzte Decke. Auf dem nahe gelegenen Marktplatz befindet sich ein Glockenturm aus dem 13. Jahrhundert mit einem Glockenspiel aus 47 Glocken und einem 83 m hohen Turm+Bruges, la capitale de la Flandre occidentale au nord-ouest de la Belgique, se distingue par ses canaux, ses rues pavées et ses édifices médiévaux. Son port, Zeebrugge, est un important centre de pêche et de commerce européen. Sur la place Burg du centre-ville, le Stadhuis (hôtel de ville) du XIVe siècle possède un plafond sculpté orné. À proximité, la place Markt abrite un beffroi du XIIIe siècle avec un carillon de 47 cloches et une tour de 83 m.+Belgiyaning shimoli-g\'arbiy qismidagi G\'arbiy Flandriya poytaxti Bryugge o\'zining kanallari, tosh toshli ko\'chalari va o\'rta asr binolari bilan ajralib turadi. Uning Zeebrugge porti baliqchilik va Yevropa savdosining muhim markazi hisoblanadi. Shahar markazidagi Burg maydonida 14-asrga oid Stadhuis (shahar hokimiyati) bezakli o\'yilgan shiftga ega. Yaqin atrofdagi Markt maydonida 13-asrga oid 47 qo\'ng\'iroqli karillon va 83 m minorasi bo\'lgan qo\'ng\'iroq minorasi joylashgan.', 'history, river, medieval', './img/brugge.jpg, ./img/brugge2.jpg, ./img/brugge3.jpg');

-- --------------------------------------------------------

--
-- Table structure for table `testing`
--

DROP TABLE IF EXISTS `testing`;
CREATE TABLE `testing` (
  `name` varchar(128) NOT NULL,
  `city` varchar(128) NOT NULL,
  `text` mediumtext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `testing`
--

INSERT INTO `testing` (`name`, `city`, `text`) VALUES
('UK', 'London', 'London is the capital'),
('Germany', 'Berlin', 'eine große Hafenstadt');

-- --------------------------------------------------------

--
-- Table structure for table `userlikes`
--

DROP TABLE IF EXISTS `userlikes`;
CREATE TABLE `userlikes` (
  `user` varchar(128) NOT NULL,
  `favorites` varchar(128) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `Username` char(255) DEFAULT NULL,
  `Password` char(255) DEFAULT NULL,
  `Loggedin` char(255) DEFAULT NULL,
  `status` varchar(10) NOT NULL DEFAULT 'Inactive',
  `ID` int(8) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`ID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `ID` int(8) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=60;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
